spring:
  application:
    name: membership-service

#  jpa:
#    open-in-view: false
#    show-sql: true
#    hibernate:
#      hbm2ddl:
#        auto: create
#      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true
